name: Release Pull Request

on:
  workflow_dispatch:
jobs:
  release:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch 100 commits to gen release note
          fetch-depth: 100

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Nx Cache
        id: nx-cache
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: nx-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            nx-${{ github.ref_name }}-
            nx-

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Prepare Monorepo-Tools
        run: pnpm run --filter @modern-js/monorepo-tools... build

      - name: Get Release Version
        id: get-release-version
        run: |
          output=$(pnpm run get-release-version)
          version=$(echo "$output" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get Release Note
        id: get-release-note
        run: |
            output=$(pnpm run gen-release-note)
            echo "release_note=$output" >> $GITHUB_OUTPUT

      - name: Bump Version
        run: |
          pnpm run bump
          pnpm install

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git checkout -b release-${{ steps.get-release-version.outputs.version }}
          git add .
          git commit -m "chorre: release ${{ steps.get-release-version.outputs.version }}"
          git push origin release-${{ steps.get-release-version.outputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release-${{ steps.get-release-version.outputs.version }}
          title: "Release: ${{ steps.get-release-version.outputs.version }}"
          body: "${{ steps.get-release-note.outputs.release_note }}"

